### PR TITLE
fix compile errors for android

### PR DESCRIPTION
**Pull request by waruqi**

### CODE REVIEW

**Comment by ThinkerYzu1** [comment]
@anakryiko Do we want to switch to elfutils from libelf?

**Comment by waruqi** [comment]
This patch is only to fix https://github.com/libbpf/libbpf-bootstrap/issues/81 because xmake uses the old libelf 0.8.13, which does not provide the GElf_Nhdr type, but the new libbpf library uses the GElf_Nhdr Nhdr.

Currently only the libelf library inside elfutils provides GElf_Nhdr

**Comment by ThinkerYzu1** [comment]
Since we actually need libelf instead of elfutils, it would be better to depend on libelf.

FYI, here is the way to fix reversion issues with xmake.
https://xmake.io/#/package/remote_package?id=install-any-version-of-the-package

**Comment by waruqi** [comment]
> Since we actually need libelf instead of elfutils, it would be better to depend on libelf.

The libelf-dev package for debian is actually from the elfutils library.

The original libelf library is, https://directory.fsf.org/wiki/Libelf, which is no longer maintained and is stuck at 0.8.13

Therefore, the libelf library on which the libbpf library relies is always elfutils.

**Comment by ThinkerYzu1** [comment]
@waruqi Thank you for the clarification.  LGTM!

**Pull request merged**
