### PR TITLE
libbpf: update to latest upstream version

### PR DESCRIPTION
**Pull request by anakryiko**
Pull in latest libbpf upstream version that contains a fix for file access checks on Android ([0]).

  [0] 830e0d017bb1 ("libbpf: Fix faccessat() usage on Android"))

Closes: https://github.com/libbpf/libbpf-bootstrap/issues/250

### CODE REVIEW

**Comment by anakryiko** [comment]
@waruqi, @slain01 latest libbpf is using `memfd_create()` libc API, which I thought it present in Android, but apparently not on all versions. Given you guys work with Android, can you please help me figure out best way to deal with it? Is there some way to detect if it's present/which version/etc? Or it would be enough to just specify minimum Android version, etc?

**Comment by waruqi** [comment]
> @waruqi, @slain01 latest libbpf is using `memfd_create()` libc API, which I thought it present in Android, but apparently not on all versions. Given you guys work with Android, can you please help me figure out best way to deal with it? Is there some way to detect if it's present/which version/etc? Or it would be enough to just specify minimum Android version, etc?

we can try to use weak symbol to detect it dynamically

```c
extern __attribute((weak)) int memfd_create(const char* _Nonnull __name, unsigned __flags);
if (memfd_create) {
    // TODO
}
```

**Comment by anakryiko** [comment]
> we can try to use weak symbol to detect it dynamically
> 
> ```c
> extern __attribute((weak)) int memfd_create(const char* _Nonnull __name, unsigned __flags);
> if (memfd_create) {
>     // TODO
> }
> ```

I ended up going a slightly other direction, but it seems to work (at least it compiles). See https://github.com/libbpf/libbpf/commit/4b3f89a68cb9db314aaf973a5f4f363386b12839

If someone with access to Android can confirm that it actually works well at runtime, I'd really appreciate it. Meanwhile I'm going to submit another patch upstream and re-sync it back into Github.

**Comment by anakryiko** [comment]
Ok, seems like we are good to go.

**Pull request merged**
